### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by claudiouzelac** [pydoit/doit-graph#7]
It would be great to have an example of loading this as a plug-in to a project and calling it as a sub-task from a command.  If you all provide the general process, I gladly do the work here.

Basically my goal is to have something along the lines of this within the `dodo.py` file:

```
def task_deps():
    return {
        'task_dep':[
            'graph'
        ],
        'targets':[
          'tasks.png'
        ],
        'actions': ['dot -Tpng %(dependencies)s -o %(targets)s'],
    }
```

When. this is executed, `doit deps`, the following output is yielded:
```
doit deps
ERROR: deps. Task dependency 'graph' does not exist.
``` 

This being said, `doit-graph` has been installed into the environment.  Strange enough, if the command, `doit graph` is executed from the same terminal, the dot file is successfully generated.

**Comment by schettino72** [comment]
This plugin provides a `command` not a `task`,  so you can not use it as a `task_dep`...
Although you could easily create a task that executes the command!

**Comment by claudiouzelac** [comment]
Thanks @schettino72.  What is the best way to do that?  I am pretty new to `doit` in general.
